# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

# Declare the orbs that we'll use in our config.
# read more about orbs: https://circleci.com/docs/2.0/using-orbs/
orbs:
  gh-pages-orb: fernfernfern/github-pages-orb@0.0.10

jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default

    steps:
      - checkout
      - run:
          name: a merge PR
          command: |
            if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
              git fetch origin +refs/pull/$CIRCLE_PR_NUMBER/merge:pr/$CIRCLE_PR_NUMBER/merge
              git checkout -qf pr/$CIRCLE_PR_NUMBER/merge
            fi

      # Download and cache dependencies
      - restore_cache:
          keys:
          - rubygems-v1-latest

      - run:
          name: Which bundler?
          command: bundle -v

      # use the gh-pages orb to build the site as in gh
      - gh-pages-orb/build-site

      - run:
          name: Jekyll build
          command: bundle exec jekyll build -d html 2> std.err

      - run:
          name: Check Jekyll build
          command: |
            cat std.err
            exit $(wc -l std.err | awk '{print $1}')

      - run:
          name: Jekyll re-build for local
          command: |
            echo "url: https://${CIRCLE_BUILD_NUM}-30926520-gh.circle-artifacts.com" > circle.yml && \
            bundle exec jekyll build -d html -b "/0/html"  --config _config.yml,circle.yml && \
            find ./html/ -type f -iname '*html' | xargs -I{} sed -i \
              -e 's|href="\(\.\/.*\/\)"|href="\1index.html"|g' \
              -e '/0\/html/ s|href="\(\/.*\/\)"|href="\1index.html"|g' {}
            # Replace pages ending on `/` from our site to direct to index.html

      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/html/index.html"; echo $DOCS_URL

      - save_cache:
          paths:
            - ~/vendor/bundle
          key: rubygems-v1-latest

      # collect reports
      - store_artifacts:
          path: ~/repo/html
          destination: html

notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci
